[package]
name = "OXIDIZE"
version = "0.1.0"
edition = "2021"

[dependencies]
sys-info = "0.9"
regex = "1.5"
users = "0.11"
image = "0.23"  # Optional for handling OS logos
termimage = "0.1"
crossterm = "0.24"  # Optional for terminal graphics