[package]
name = "oxifetch"
version = "0.0.7"
authors = ["AK1R4S4T0H <ak1r4s4t0h@proton.me>"]
edition = "2021"
description = "OxiFetch is a Rust program that displays key system information, such as OS details, uptime, CPU specs, memory usage, and more. The output includes an ASCII art logo and a quick overview of your machine's current status."
license = "GPL-3.0"
repository = "https://github.com/AK1R4S4T0H/OxiFetch"

[dependencies]
sys-info = "0.9"
regex = "1.5"
users = "0.11"

[[bin]]
name = "oxifetch"
path = "src/main.rs"
